curl \     
-X POST \
-H "Accept: application/vnd.github+json" \
-H "Authorization: Bearer <YOUR_GITHUB_ACTION>"\
-H "X-GitHub-Api-Version: 2022-11-28" \
https://api.github.com/repos/Slu1314/Trickster/actions/workflows/github_linux_ubuntu.yaml/dispatches \
-d '{"ref":"main","inputs":{"token":"00e3b1478b7285dc96f2ea761c1f89f3","type": "linux"}'
